"""Structured-control public data structures and deterministic pretty-printers."""

from tiny_dec.structuring.models import (
    FunctionStructuredFacts,
    ProgramStructuredFacts,
    StructuredBlock,
    StructuredBreak,
    StructuredContinue,
    StructuredGoto,
    StructuredIf,
    StructuredSequence,
    StructuredStmt,
    StructuredSwitch,
    StructuredSwitchCase,
    StructuredWhile,
)
from tiny_dec.structuring.pretty import (
    format_function_structured_facts,
    format_program_structured_facts,
    format_structured_block,
    format_structured_break,
    format_structured_continue,
    format_structured_goto,
    format_structured_if,
    format_structured_sequence,
    format_structured_switch,
    format_structured_switch_case,
    format_structured_while,
)
from tiny_dec.structuring.transform import (
    analyze_function_structuring,
    analyze_program_structuring,
    build_function_structured_facts,
    build_program_structured_facts,
)

__all__ = [
    "StructuredBlock",
    "StructuredGoto",
    "StructuredBreak",
    "StructuredContinue",
    "StructuredSequence",
    "StructuredIf",
    "StructuredSwitchCase",
    "StructuredSwitch",
    "StructuredWhile",
    "StructuredStmt",
    "FunctionStructuredFacts",
    "ProgramStructuredFacts",
    "format_structured_block",
    "format_structured_goto",
    "format_structured_break",
    "format_structured_continue",
    "format_structured_if",
    "format_structured_switch_case",
    "format_structured_switch",
    "format_structured_while",
    "format_structured_sequence",
    "format_function_structured_facts",
    "format_program_structured_facts",
    "analyze_function_structuring",
    "analyze_program_structuring",
    "build_function_structured_facts",
    "build_program_structured_facts",
]
